baseURL = "/"
languageCode = "en-us"
summaryLength = "10"
theme = "kross-hugo"
title = "Astyltsvig | Software consultant"
[[menu.main]]
URL = "about"
name = "About"
weight = 2
[[menu.main]]
URL = "blog"
name = "Blog"
weight = 3
[params]
address = "Byhøjen 28, 3tv 2720 Vanløse,"
author = "Andreas Styltsvig"
copyright = ""
description = ""
email = "astyltsvig@gmail.com"
google_analitycs_id = ""
home = "Home"
logo = "images/logo.png"
phone = "+4531150424 (SMS ONLY)"
theme_color = "#41228e"
[params.contact]
enable = false
form_action = "#"
[[params.plugins.css]]
URL = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
URL = "plugins/slick/slick.css"
[[params.plugins.css]]
URL = "plugins/themify-icons/themify-icons.css"
[[params.plugins.js]]
URL = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
URL = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
URL = "plugins/slick/slick.min.js"
[[params.plugins.js]]
URL = "plugins/shuffle/shuffle.min.js"
[params.preloader]
enable = true
preloader = ""
[[params.social]]
URL = "https://www.linkedin.com/in/andreas-styltsvig-b03688119/"
icon = "ti-linkedin"
[[params.social]]
URL = "https://github.com/astyltsvig"
icon = "ti-github"
